// Code generated by protoc-gen-go. DO NOT EDIT.
// source: NormalizeRecord.proto

/*
Package oip5 is a generated protocol buffer package.

It is generated from these files:
	NormalizeRecord.proto
	oip5.proto
	Record.proto
	RecordTemplateProto.proto

It has these top-level messages:
	NormalizeRecordProto
	NormalField
	Field
	OipFive
	Transfer
	Deactivate
	Edit
	RecordProto
	Permissions
	Payment
	OipDetails
	RecordTemplateProto
*/
package oip5

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// https://github.com/golang/protobuf/blob/882cf97/protoc-gen-go/descriptor/descriptor.proto#L136-L168
type Field_Type int32

const (
	// 0 is reserved for errors.
	Field_TYPE_ERROR Field_Type = 0
	// Order is weird for historical reasons.
	Field_TYPE_DOUBLE Field_Type = 1
	Field_TYPE_FLOAT  Field_Type = 2
	// Not ZigZag encoded.  Negative numbers take 10 bytes.  Use TYPE_SINT64 if
	// negative values are likely.
	Field_TYPE_INT64  Field_Type = 3
	Field_TYPE_UINT64 Field_Type = 4
	// Not ZigZag encoded.  Negative numbers take 10 bytes.  Use TYPE_SINT32 if
	// negative values are likely.
	Field_TYPE_INT32   Field_Type = 5
	Field_TYPE_FIXED64 Field_Type = 6
	Field_TYPE_FIXED32 Field_Type = 7
	Field_TYPE_BOOL    Field_Type = 8
	Field_TYPE_STRING  Field_Type = 9
	// Tag-delimited aggregate.
	// Group type is deprecated and not supported in proto3. However, Proto3
	// implementations should still be able to parse the group wire format and
	// treat group fields as unknown fields.
	Field_TYPE_GROUP   Field_Type = 10
	Field_TYPE_MESSAGE Field_Type = 11
	// New in version 2.
	Field_TYPE_BYTES    Field_Type = 12
	Field_TYPE_UINT32   Field_Type = 13
	Field_TYPE_ENUM     Field_Type = 14
	Field_TYPE_SFIXED32 Field_Type = 15
	Field_TYPE_SFIXED64 Field_Type = 16
	Field_TYPE_SINT32   Field_Type = 17
	Field_TYPE_SINT64   Field_Type = 18
)

var Field_Type_name = map[int32]string{
	0:  "TYPE_ERROR",
	1:  "TYPE_DOUBLE",
	2:  "TYPE_FLOAT",
	3:  "TYPE_INT64",
	4:  "TYPE_UINT64",
	5:  "TYPE_INT32",
	6:  "TYPE_FIXED64",
	7:  "TYPE_FIXED32",
	8:  "TYPE_BOOL",
	9:  "TYPE_STRING",
	10: "TYPE_GROUP",
	11: "TYPE_MESSAGE",
	12: "TYPE_BYTES",
	13: "TYPE_UINT32",
	14: "TYPE_ENUM",
	15: "TYPE_SFIXED32",
	16: "TYPE_SFIXED64",
	17: "TYPE_SINT32",
	18: "TYPE_SINT64",
}
var Field_Type_value = map[string]int32{
	"TYPE_ERROR":    0,
	"TYPE_DOUBLE":   1,
	"TYPE_FLOAT":    2,
	"TYPE_INT64":    3,
	"TYPE_UINT64":   4,
	"TYPE_INT32":    5,
	"TYPE_FIXED64":  6,
	"TYPE_FIXED32":  7,
	"TYPE_BOOL":     8,
	"TYPE_STRING":   9,
	"TYPE_GROUP":    10,
	"TYPE_MESSAGE":  11,
	"TYPE_BYTES":    12,
	"TYPE_UINT32":   13,
	"TYPE_ENUM":     14,
	"TYPE_SFIXED32": 15,
	"TYPE_SFIXED64": 16,
	"TYPE_SINT32":   17,
	"TYPE_SINT64":   18,
}

func (x Field_Type) String() string {
	return proto.EnumName(Field_Type_name, int32(x))
}
func (Field_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type NormalizeRecordProto struct {
	// standard template ID which triggers this meta-type
	MainTemplate uint64 `protobuf:"varint,1,opt,name=mainTemplate" json:"mainTemplate,omitempty"`
	// fields comprising this new meta-type
	Fields []*NormalField `protobuf:"bytes,2,rep,name=fields" json:"fields,omitempty"`
}

func (m *NormalizeRecordProto) Reset()                    { *m = NormalizeRecordProto{} }
func (m *NormalizeRecordProto) String() string            { return proto.CompactTextString(m) }
func (*NormalizeRecordProto) ProtoMessage()               {}
func (*NormalizeRecordProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NormalizeRecordProto) GetMainTemplate() uint64 {
	if m != nil {
		return m.MainTemplate
	}
	return 0
}

func (m *NormalizeRecordProto) GetFields() []*NormalField {
	if m != nil {
		return m.Fields
	}
	return nil
}

type NormalField struct {
	// new ES compatible name
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// path to the source value
	Path []*Field `protobuf:"bytes,2,rep,name=path" json:"path,omitempty"`
}

func (m *NormalField) Reset()                    { *m = NormalField{} }
func (m *NormalField) String() string            { return proto.CompactTextString(m) }
func (*NormalField) ProtoMessage()               {}
func (*NormalField) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NormalField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NormalField) GetPath() []*Field {
	if m != nil {
		return m.Path
	}
	return nil
}

type Field struct {
	// Tag number in prior Proto message
	Tag int32 `protobuf:"varint,1,opt,name=tag" json:"tag,omitempty"`
	// Expected type
	// if type_message resolution proceeds into the message
	// if type_message and type_name == oipProto.txid resolves linked record before proceeding
	// if type doesn't match field is ignored
	Type Field_Type `protobuf:"varint,2,opt,name=type,enum=oipProto.Field_Type" json:"type,omitempty"`
	// Enter specified details template
	// Set either tag/type OR template
	Template uint64 `protobuf:"varint,3,opt,name=template" json:"template,omitempty"`
}

func (m *Field) Reset()                    { *m = Field{} }
func (m *Field) String() string            { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()               {}
func (*Field) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Field) GetTag() int32 {
	if m != nil {
		return m.Tag
	}
	return 0
}

func (m *Field) GetType() Field_Type {
	if m != nil {
		return m.Type
	}
	return Field_TYPE_ERROR
}

func (m *Field) GetTemplate() uint64 {
	if m != nil {
		return m.Template
	}
	return 0
}

func init() {
	proto.RegisterType((*NormalizeRecordProto)(nil), "oipProto.NormalizeRecordProto")
	proto.RegisterType((*NormalField)(nil), "oipProto.NormalField")
	proto.RegisterType((*Field)(nil), "oipProto.Field")
	proto.RegisterEnum("oipProto.Field_Type", Field_Type_name, Field_Type_value)
}

func init() { proto.RegisterFile("NormalizeRecord.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0xcd, 0x6e, 0x9b, 0x40,
	0x10, 0xc7, 0xcb, 0x87, 0xa9, 0x3d, 0xf8, 0x63, 0xb2, 0x4a, 0x24, 0xab, 0x27, 0x8b, 0x5e, 0xb8,
	0x94, 0x03, 0x50, 0xee, 0x41, 0x59, 0x5b, 0x96, 0x1c, 0xb0, 0x16, 0x90, 0x9a, 0x5e, 0x2a, 0xda,
	0xd0, 0x16, 0xc9, 0x18, 0xe4, 0x72, 0x71, 0x9f, 0xa8, 0x4f, 0xd2, 0xe7, 0x8a, 0xd8, 0xb5, 0xd7,
	0xc6, 0xb7, 0x99, 0xdf, 0xfe, 0xf9, 0xcd, 0x8c, 0x04, 0x3c, 0x44, 0xf5, 0xa1, 0xca, 0x77, 0xe5,
	0xdf, 0x82, 0x15, 0x3f, 0xea, 0xc3, 0xab, 0xd3, 0x1c, 0xea, 0xb6, 0x26, 0xc3, 0xba, 0x6c, 0xb6,
	0x5d, 0x65, 0x95, 0x70, 0x7f, 0x13, 0xe1, 0x9c, 0x58, 0x30, 0xae, 0xf2, 0x72, 0x9f, 0x16, 0x55,
	0xb3, 0xcb, 0xdb, 0x62, 0xae, 0x2c, 0x14, 0x5b, 0x67, 0x3d, 0x46, 0x3e, 0x81, 0xf1, 0xb3, 0x2c,
	0x76, 0xaf, 0x7f, 0xe6, 0xea, 0x42, 0xb3, 0x4d, 0xf7, 0xc1, 0x39, 0x6b, 0x1d, 0xe1, 0x5c, 0x76,
	0xaf, 0xec, 0x14, 0xb2, 0x96, 0x60, 0x5e, 0x61, 0x42, 0x40, 0xdf, 0xe7, 0x95, 0x30, 0x8f, 0x18,
	0xaf, 0xc9, 0x47, 0xd0, 0x9b, 0xbc, 0xfd, 0x7d, 0xf2, 0xcd, 0x2e, 0x3e, 0x61, 0xe2, 0x8f, 0xd6,
	0x3f, 0x0d, 0x06, 0x42, 0x81, 0xa0, 0xb5, 0xf9, 0x2f, 0x6e, 0x18, 0xb0, 0xae, 0x24, 0x36, 0xe8,
	0xed, 0xb1, 0x29, 0xe6, 0xea, 0x42, 0xb1, 0xa7, 0xee, 0xfd, 0x8d, 0xc0, 0x49, 0x8f, 0x4d, 0xc1,
	0x78, 0x82, 0x7c, 0x80, 0x61, 0x7b, 0x3e, 0x4e, 0xe3, 0xc7, 0xc9, 0xde, 0xfa, 0xaf, 0x82, 0xde,
	0x45, 0xc9, 0x14, 0x20, 0x7d, 0xd9, 0xd2, 0x6f, 0x94, 0xb1, 0x98, 0xe1, 0x3b, 0x32, 0x03, 0x93,
	0xf7, 0x4f, 0x71, 0x16, 0x6e, 0x28, 0x2a, 0x32, 0xb0, 0xdc, 0xc4, 0x8f, 0x29, 0xaa, 0xb2, 0x5f,
	0x47, 0x69, 0xe0, 0xa3, 0x26, 0x3f, 0xc8, 0x04, 0xd0, 0xaf, 0x03, 0x9e, 0x8b, 0x03, 0x82, 0x30,
	0x16, 0x82, 0xf5, 0x17, 0xfa, 0x14, 0xf8, 0x68, 0xf4, 0x89, 0xe7, 0xe2, 0x7b, 0x32, 0x81, 0x11,
	0x27, 0x61, 0x1c, 0x6f, 0x70, 0x28, 0x9d, 0x49, 0xca, 0xd6, 0xd1, 0x0a, 0x47, 0xd2, 0xb9, 0x62,
	0x71, 0xb6, 0x45, 0x90, 0x86, 0x67, 0x9a, 0x24, 0x8f, 0x2b, 0x8a, 0xa6, 0x4c, 0x84, 0x2f, 0x29,
	0x4d, 0x70, 0xdc, 0x5b, 0xcb, 0x73, 0x71, 0x22, 0x47, 0xd0, 0x28, 0x7b, 0xc6, 0x29, 0xb9, 0x83,
	0x89, 0x18, 0x71, 0x5e, 0x62, 0x76, 0x83, 0x02, 0x1f, 0xf1, 0xb2, 0x88, 0xb0, 0xdc, 0xf5, 0x40,
	0xe0, 0x23, 0x09, 0x8d, 0xaf, 0x7a, 0x5d, 0x36, 0x9f, 0xbf, 0x1b, 0xfc, 0xb7, 0xf3, 0xde, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x04, 0x8a, 0x9a, 0x3e, 0x8f, 0x02, 0x00, 0x00,
}
