// Code generated by protoc-gen-go. DO NOT EDIT.
// source: oip5.proto

/*
Package oip5 is a generated protocol buffer package.

It is generated from these files:
	oip5.proto
	RecordTemplateProto.proto
	Record.proto
	tmpl_0000000deadbeef.proto

It has these top-level messages:
	OipFive
	Transfer
	Deactivate
	Edit
	RecordTemplateProto
	RecordProto
	Payment
	Storage
	File
	OipDetails
	Tmpl_00000000Deadbeef
*/
package oip5

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OipFive struct {
	RecordTemplate *RecordTemplateProto `protobuf:"bytes,1,opt,name=recordTemplate" json:"recordTemplate,omitempty"`
	Record         *RecordProto         `protobuf:"bytes,2,opt,name=record" json:"record,omitempty"`
	Transfer       *Transfer            `protobuf:"bytes,7,opt,name=transfer" json:"transfer,omitempty"`
	Deactivate     *Deactivate          `protobuf:"bytes,8,opt,name=deactivate" json:"deactivate,omitempty"`
	Edit           *Edit                `protobuf:"bytes,9,opt,name=edit" json:"edit,omitempty"`
}

func (m *OipFive) Reset()                    { *m = OipFive{} }
func (m *OipFive) String() string            { return proto.CompactTextString(m) }
func (*OipFive) ProtoMessage()               {}
func (*OipFive) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *OipFive) GetRecordTemplate() *RecordTemplateProto {
	if m != nil {
		return m.RecordTemplate
	}
	return nil
}

func (m *OipFive) GetRecord() *RecordProto {
	if m != nil {
		return m.Record
	}
	return nil
}

func (m *OipFive) GetTransfer() *Transfer {
	if m != nil {
		return m.Transfer
	}
	return nil
}

func (m *OipFive) GetDeactivate() *Deactivate {
	if m != nil {
		return m.Deactivate
	}
	return nil
}

func (m *OipFive) GetEdit() *Edit {
	if m != nil {
		return m.Edit
	}
	return nil
}

type Transfer struct {
}

func (m *Transfer) Reset()                    { *m = Transfer{} }
func (m *Transfer) String() string            { return proto.CompactTextString(m) }
func (*Transfer) ProtoMessage()               {}
func (*Transfer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Deactivate struct {
}

func (m *Deactivate) Reset()                    { *m = Deactivate{} }
func (m *Deactivate) String() string            { return proto.CompactTextString(m) }
func (*Deactivate) ProtoMessage()               {}
func (*Deactivate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Edit struct {
}

func (m *Edit) Reset()                    { *m = Edit{} }
func (m *Edit) String() string            { return proto.CompactTextString(m) }
func (*Edit) ProtoMessage()               {}
func (*Edit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*OipFive)(nil), "oip5.OipFive")
	proto.RegisterType((*Transfer)(nil), "oip5.Transfer")
	proto.RegisterType((*Deactivate)(nil), "oip5.Deactivate")
	proto.RegisterType((*Edit)(nil), "oip5.Edit")
}

func init() { proto.RegisterFile("oip5.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xb1, 0x4a, 0xc7, 0x30,
	0x10, 0xc6, 0x69, 0x29, 0x69, 0x3d, 0x4b, 0x91, 0x4c, 0xb1, 0x83, 0x94, 0x4c, 0xe2, 0x50, 0x8a,
	0xe2, 0x0b, 0x88, 0x8a, 0x9b, 0x12, 0x3a, 0xb9, 0xd5, 0x26, 0x42, 0x40, 0x4d, 0x88, 0xa1, 0x2f,
	0xe0, 0x8b, 0x4b, 0xee, 0x6a, 0xd5, 0x3f, 0xdd, 0x92, 0xdf, 0xfd, 0xbe, 0x2f, 0xe1, 0x00, 0x9c,
	0xf5, 0xd7, 0xbd, 0x0f, 0x2e, 0x3a, 0x5e, 0xa4, 0x73, 0x5b, 0x2b, 0x33, 0xbb, 0xa0, 0x89, 0xb5,
	0xa7, 0x74, 0x1b, 0xcd, 0xbb, 0x7f, 0x9b, 0xa2, 0x79, 0x4a, 0x90, 0x46, 0xf2, 0x2b, 0x87, 0xf2,
	0xd1, 0xfa, 0x7b, 0xbb, 0x18, 0xfe, 0x00, 0x4d, 0xf8, 0x27, 0x8a, 0xac, 0xcb, 0xce, 0x8f, 0x2f,
	0xbb, 0x1e, 0xfb, 0x69, 0xd6, 0xef, 0x74, 0xa9, 0x83, 0x1c, 0x1f, 0x80, 0x11, 0x11, 0x39, 0x36,
	0x88, 0x9d, 0x06, 0x4a, 0xae, 0x1e, 0xbf, 0x80, 0x2a, 0x86, 0xe9, 0xe3, 0xf3, 0xd5, 0x04, 0x51,
	0x62, 0xa6, 0xa1, 0xcc, 0xb8, 0x52, 0xb5, 0xcd, 0xf9, 0x00, 0xa0, 0xcd, 0x34, 0x47, 0xbb, 0xa4,
	0x3f, 0x56, 0x68, 0x9f, 0x90, 0x7d, 0xbb, 0x71, 0xf5, 0xc7, 0xe1, 0x67, 0x50, 0x18, 0x6d, 0xa3,
	0x38, 0x42, 0x17, 0xc8, 0xbd, 0xd3, 0x36, 0x2a, 0xe4, 0x12, 0xa0, 0xfa, 0x79, 0x47, 0xd6, 0x00,
	0xbf, 0x2d, 0x92, 0x41, 0x91, 0xbc, 0x1b, 0xf6, 0x8c, 0x8b, 0x7d, 0x61, 0xb8, 0xb6, 0xab, 0xef,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x79, 0xa3, 0x36, 0xdf, 0x73, 0x01, 0x00, 0x00,
}
