// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Record.proto

package oip5

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Network int32

const (
	Network_UNKNOWN_NETWORK Network = 0
	// https://ipfs.io
	Network_IPFS Network = 1
	// https://webtorrent.io
	Network_WEB_TORRENT Network = 2
	// http(s)://
	Network_HTTP Network = 3
)

var Network_name = map[int32]string{
	0: "UNKNOWN_NETWORK",
	1: "IPFS",
	2: "WEB_TORRENT",
	3: "HTTP",
}
var Network_value = map[string]int32{
	"UNKNOWN_NETWORK": 0,
	"IPFS":            1,
	"WEB_TORRENT":     2,
	"HTTP":            3,
}

func (x Network) String() string {
	return proto.EnumName(Network_name, int32(x))
}
func (Network) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type RecordProto struct {
	// Record title
	Title string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	// Record description
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	// Original publication year
	Year int64 `protobuf:"varint,3,opt,name=year" json:"year,omitempty"`
	// Searchable user-tags
	Tags []string `protobuf:"bytes,4,rep,name=tags" json:"tags,omitempty"`
	// Files and locations
	Storage *Storage `protobuf:"bytes,5,opt,name=storage" json:"storage,omitempty"`
	// Payment terms
	Payment *Payment `protobuf:"bytes,6,opt,name=payment" json:"payment,omitempty"`
	// Record specific additional information
	Details *OipDetails `protobuf:"bytes,7,opt,name=details" json:"details,omitempty"`
}

func (m *RecordProto) Reset()                    { *m = RecordProto{} }
func (m *RecordProto) String() string            { return proto.CompactTextString(m) }
func (*RecordProto) ProtoMessage()               {}
func (*RecordProto) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *RecordProto) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *RecordProto) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *RecordProto) GetYear() int64 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *RecordProto) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *RecordProto) GetStorage() *Storage {
	if m != nil {
		return m.Storage
	}
	return nil
}

func (m *RecordProto) GetPayment() *Payment {
	if m != nil {
		return m.Payment
	}
	return nil
}

func (m *RecordProto) GetDetails() *OipDetails {
	if m != nil {
		return m.Details
	}
	return nil
}

type Payment struct {
}

func (m *Payment) Reset()                    { *m = Payment{} }
func (m *Payment) String() string            { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()               {}
func (*Payment) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

type Storage struct {
	// Storage distribution network providing files
	Network Network `protobuf:"varint,1,opt,name=network,enum=oip5.record.Network" json:"network,omitempty"`
	// Network specific identifier to locate files
	Location string `protobuf:"bytes,2,opt,name=location" json:"location,omitempty"`
	// Set of files contained within record
	Files []*File `protobuf:"bytes,3,rep,name=files" json:"files,omitempty"`
}

func (m *Storage) Reset()                    { *m = Storage{} }
func (m *Storage) String() string            { return proto.CompactTextString(m) }
func (*Storage) ProtoMessage()               {}
func (*Storage) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *Storage) GetNetwork() Network {
	if m != nil {
		return m.Network
	}
	return Network_UNKNOWN_NETWORK
}

func (m *Storage) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Storage) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

type File struct {
	// Human readable file name
	DisplayName string `protobuf:"bytes,1,opt,name=displayName" json:"displayName,omitempty"`
	// Where to find file from storage.location
	FilePath string `protobuf:"bytes,2,opt,name=filePath" json:"filePath,omitempty"`
	// Byte size of file
	Size uint64 `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	// MIME Type
	// https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types
	ContentType string `protobuf:"bytes,4,opt,name=contentType" json:"contentType,omitempty"`
	// File specific additional information
	Details []*google_protobuf.Any `protobuf:"bytes,5,rep,name=details" json:"details,omitempty"`
	// Override parent storage object if file is located elsewhere
	Storage *Storage `protobuf:"bytes,6,opt,name=storage" json:"storage,omitempty"`
	// Override file specific payment details
	Payment *Payment `protobuf:"bytes,7,opt,name=payment" json:"payment,omitempty"`
}

func (m *File) Reset()                    { *m = File{} }
func (m *File) String() string            { return proto.CompactTextString(m) }
func (*File) ProtoMessage()               {}
func (*File) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *File) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *File) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func (m *File) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *File) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *File) GetDetails() []*google_protobuf.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *File) GetStorage() *Storage {
	if m != nil {
		return m.Storage
	}
	return nil
}

func (m *File) GetPayment() *Payment {
	if m != nil {
		return m.Payment
	}
	return nil
}

type OipDetails struct {
	Details []*google_protobuf.Any `protobuf:"bytes,1,rep,name=details" json:"details,omitempty"`
}

func (m *OipDetails) Reset()                    { *m = OipDetails{} }
func (m *OipDetails) String() string            { return proto.CompactTextString(m) }
func (*OipDetails) ProtoMessage()               {}
func (*OipDetails) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *OipDetails) GetDetails() []*google_protobuf.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

func init() {
	proto.RegisterType((*RecordProto)(nil), "oip5.record.RecordProto")
	proto.RegisterType((*Payment)(nil), "oip5.record.Payment")
	proto.RegisterType((*Storage)(nil), "oip5.record.Storage")
	proto.RegisterType((*File)(nil), "oip5.record.File")
	proto.RegisterType((*OipDetails)(nil), "oip5.record.OipDetails")
	proto.RegisterEnum("oip5.record.Network", Network_name, Network_value)
}

func init() { proto.RegisterFile("Record.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 446 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0x26, 0x4d, 0xda, 0xac, 0x2f, 0x88, 0x15, 0x53, 0x09, 0xb3, 0x53, 0x94, 0x0b, 0x11, 0x07,
	0x4f, 0x0c, 0x71, 0xe3, 0xc2, 0xa0, 0x13, 0x68, 0x52, 0x1a, 0xb9, 0x41, 0x95, 0xb8, 0x4c, 0x5e,
	0xea, 0x05, 0x8b, 0x2c, 0x8e, 0x12, 0x23, 0x14, 0x0e, 0x88, 0x33, 0x7f, 0x35, 0xb2, 0x3d, 0x6f,
	0x19, 0xe2, 0x50, 0x6e, 0xef, 0xbd, 0xef, 0x7b, 0x3f, 0xfc, 0x7d, 0x86, 0x87, 0x94, 0x97, 0xb2,
	0xdb, 0x91, 0xb6, 0x93, 0x4a, 0xa2, 0x48, 0x8a, 0xf6, 0x35, 0xe9, 0x4c, 0xe9, 0xe8, 0x59, 0x25,
	0x65, 0x55, 0xf3, 0x63, 0x03, 0x5d, 0x7e, 0xbb, 0x3a, 0x66, 0xcd, 0x60, 0x79, 0xc9, 0xaf, 0x09,
	0x44, 0xb6, 0x31, 0x37, 0x7d, 0x4b, 0x98, 0x2a, 0xa1, 0x6a, 0x8e, 0xbd, 0xd8, 0x4b, 0xe7, 0xd4,
	0x26, 0x28, 0x86, 0x68, 0xc7, 0xfb, 0xb2, 0x13, 0xad, 0x12, 0xb2, 0xc1, 0x13, 0x83, 0x8d, 0x4b,
	0x08, 0x41, 0x30, 0x70, 0xd6, 0x61, 0x3f, 0xf6, 0x52, 0x9f, 0x9a, 0x58, 0xd7, 0x14, 0xab, 0x7a,
	0x1c, 0xc4, 0x7e, 0x3a, 0xa7, 0x26, 0x46, 0x04, 0xc2, 0x5e, 0xc9, 0x8e, 0x55, 0x1c, 0x4f, 0x63,
	0x2f, 0x8d, 0x4e, 0x96, 0x64, 0x74, 0x29, 0xd9, 0x58, 0x8c, 0x3a, 0x92, 0xe6, 0xb7, 0x6c, 0xb8,
	0xe6, 0x8d, 0xc2, 0xb3, 0x7f, 0xf0, 0x73, 0x8b, 0x51, 0x47, 0x42, 0x2f, 0x21, 0xdc, 0x71, 0xc5,
	0x44, 0xdd, 0xe3, 0xd0, 0xf0, 0x9f, 0xde, 0xe3, 0xaf, 0x45, 0xfb, 0xde, 0xc2, 0xd4, 0xf1, 0x92,
	0x39, 0x84, 0x37, 0x63, 0x92, 0x9f, 0x10, 0x6e, 0xee, 0x16, 0x37, 0x5c, 0x7d, 0x97, 0xdd, 0x57,
	0x23, 0xc5, 0xa3, 0xbf, 0x16, 0x67, 0x16, 0xa3, 0x8e, 0x84, 0x8e, 0xe0, 0xa0, 0x96, 0x25, 0x1b,
	0xe9, 0x73, 0x9b, 0xa3, 0xe7, 0x30, 0xbd, 0x12, 0x35, 0xef, 0xb1, 0x1f, 0xfb, 0x69, 0x74, 0xf2,
	0xf8, 0xde, 0xa4, 0x33, 0x51, 0x73, 0x6a, 0xf1, 0xe4, 0xf7, 0x04, 0x02, 0x9d, 0x1b, 0xc1, 0x45,
	0xdf, 0xd6, 0x6c, 0xc8, 0xd8, 0xb5, 0x33, 0x63, 0x5c, 0xd2, 0xfb, 0x74, 0x4f, 0xce, 0xd4, 0x17,
	0xb7, 0xcf, 0xe5, 0x5a, 0xf8, 0x5e, 0xfc, 0xe0, 0xc6, 0x8c, 0x80, 0x9a, 0x58, 0x4f, 0x2c, 0x65,
	0xa3, 0x78, 0xa3, 0x8a, 0xa1, 0xe5, 0x38, 0xb0, 0x13, 0x47, 0x25, 0xfd, 0x62, 0x27, 0xdd, 0xd4,
	0xdc, 0xb9, 0x24, 0xf6, 0xdf, 0x10, 0xf7, 0x6f, 0xc8, 0xdb, 0x66, 0xb8, 0xd5, 0x6d, 0x6c, 0xe5,
	0xec, 0x3f, 0xad, 0x0c, 0xf7, 0xb0, 0x32, 0x79, 0x03, 0x70, 0x67, 0xd7, 0xf8, 0x3a, 0x6f, 0x8f,
	0xeb, 0x5e, 0xbc, 0x83, 0xf0, 0xc6, 0x23, 0xf4, 0x04, 0x0e, 0x3f, 0x65, 0xe7, 0xd9, 0x7a, 0x9b,
	0x5d, 0x64, 0xab, 0x62, 0xbb, 0xa6, 0xe7, 0x8b, 0x07, 0xe8, 0x00, 0x82, 0x8f, 0xf9, 0xd9, 0x66,
	0xe1, 0xa1, 0x43, 0x88, 0xb6, 0xab, 0xd3, 0x8b, 0x62, 0x4d, 0xe9, 0x2a, 0x2b, 0x16, 0x13, 0x0d,
	0x7d, 0x28, 0x8a, 0x7c, 0xe1, 0x9f, 0xce, 0x3e, 0x07, 0xfa, 0xc4, 0xcb, 0x99, 0xd9, 0xf1, 0xea,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xec, 0xf3, 0xc6, 0x27, 0x64, 0x03, 0x00, 0x00,
}
