// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Record.proto

package oip5

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RecordProto struct {
	// Searchable user-tags
	Tags []string `protobuf:"bytes,4,rep,name=tags" json:"tags,omitempty"`
	// Payment terms
	Payment *Payment `protobuf:"bytes,6,opt,name=payment" json:"payment,omitempty"`
	// Record specific additional information
	Details     *OipDetails  `protobuf:"bytes,7,opt,name=details" json:"details,omitempty"`
	Permissions *Permissions `protobuf:"bytes,8,opt,name=permissions" json:"permissions,omitempty"`
}

func (m *RecordProto) Reset()                    { *m = RecordProto{} }
func (m *RecordProto) String() string            { return proto.CompactTextString(m) }
func (*RecordProto) ProtoMessage()               {}
func (*RecordProto) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *RecordProto) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *RecordProto) GetPayment() *Payment {
	if m != nil {
		return m.Payment
	}
	return nil
}

func (m *RecordProto) GetDetails() *OipDetails {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *RecordProto) GetPermissions() *Permissions {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type Txid struct {
	Raw []byte `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
}

func (m *Txid) Reset()                    { *m = Txid{} }
func (m *Txid) String() string            { return proto.CompactTextString(m) }
func (*Txid) ProtoMessage()               {}
func (*Txid) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Txid) GetRaw() []byte {
	if m != nil {
		return m.Raw
	}
	return nil
}

type Permissions struct {
}

func (m *Permissions) Reset()                    { *m = Permissions{} }
func (m *Permissions) String() string            { return proto.CompactTextString(m) }
func (*Permissions) ProtoMessage()               {}
func (*Permissions) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type Payment struct {
}

func (m *Payment) Reset()                    { *m = Payment{} }
func (m *Payment) String() string            { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()               {}
func (*Payment) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

type OipDetails struct {
	Details []*google_protobuf.Any `protobuf:"bytes,1,rep,name=details" json:"details,omitempty"`
}

func (m *OipDetails) Reset()                    { *m = OipDetails{} }
func (m *OipDetails) String() string            { return proto.CompactTextString(m) }
func (*OipDetails) ProtoMessage()               {}
func (*OipDetails) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *OipDetails) GetDetails() []*google_protobuf.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

func init() {
	proto.RegisterType((*RecordProto)(nil), "oip5.record.RecordProto")
	proto.RegisterType((*Txid)(nil), "oip5.record.Txid")
	proto.RegisterType((*Permissions)(nil), "oip5.record.Permissions")
	proto.RegisterType((*Payment)(nil), "oip5.record.Payment")
	proto.RegisterType((*OipDetails)(nil), "oip5.record.OipDetails")
}

func init() { proto.RegisterFile("Record.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x09, 0x2d, 0xad, 0x3b, 0x59, 0x41, 0x82, 0x60, 0xf4, 0x54, 0x72, 0xea, 0x29, 0x8b,
	0x8a, 0x17, 0xf1, 0xa2, 0x78, 0x77, 0x09, 0x9e, 0xbc, 0x65, 0x6d, 0x2c, 0x81, 0xdd, 0x26, 0x24,
	0x15, 0xed, 0xdb, 0xf9, 0x68, 0xd2, 0x89, 0x75, 0xdb, 0xdb, 0xd0, 0xff, 0xfb, 0x9b, 0x6f, 0x06,
	0xd6, 0xca, 0xbc, 0xbb, 0xd0, 0x48, 0x1f, 0x5c, 0xef, 0x18, 0x75, 0xd6, 0xdf, 0xc9, 0x80, 0x9f,
	0xae, 0x2e, 0x5b, 0xe7, 0xda, 0xbd, 0xd9, 0x60, 0xb4, 0xfb, 0xfc, 0xd8, 0xe8, 0x6e, 0x48, 0x9c,
	0xf8, 0x21, 0x40, 0x53, 0x71, 0x8b, 0x3d, 0x06, 0x79, 0xaf, 0xdb, 0xc8, 0xf3, 0x2a, 0xab, 0x57,
	0x0a, 0x67, 0x26, 0xa1, 0xf4, 0x7a, 0x38, 0x98, 0xae, 0xe7, 0x45, 0x45, 0x6a, 0x7a, 0x73, 0x2e,
	0x67, 0x7f, 0x97, 0xdb, 0x94, 0xa9, 0x09, 0x62, 0xd7, 0x50, 0x36, 0xa6, 0xd7, 0x76, 0x1f, 0x79,
	0x89, 0xfc, 0xc5, 0x82, 0x7f, 0xb1, 0xfe, 0x39, 0xc5, 0x6a, 0xe2, 0xd8, 0x3d, 0x50, 0x6f, 0xc2,
	0xc1, 0xc6, 0x68, 0x5d, 0x17, 0xf9, 0x09, 0xd6, 0xf8, 0xf2, 0x99, 0x63, 0xae, 0xe6, 0xb0, 0xe0,
	0x90, 0xbf, 0x7e, 0xdb, 0x86, 0x9d, 0x41, 0x16, 0xf4, 0x17, 0x27, 0x15, 0xa9, 0xd7, 0x6a, 0x1c,
	0xc5, 0x29, 0xd0, 0x59, 0x4b, 0xac, 0xa0, 0xfc, 0x73, 0x15, 0x0f, 0x00, 0x47, 0x8d, 0x71, 0xc1,
	0x49, 0x98, 0x54, 0x19, 0x2e, 0x98, 0x2e, 0x26, 0xa7, 0x8b, 0xc9, 0xc7, 0x6e, 0xf8, 0xb7, 0x7d,
	0x2a, 0xde, 0xf2, 0xd1, 0x6c, 0x57, 0x60, 0x7c, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x1e, 0xbd,
	0xde, 0x42, 0x7b, 0x01, 0x00, 0x00,
}
