// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tmpl_0000000deadbeef.proto

package oip5

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Research Protocol
type Tmpl_00000000DEADBEEF struct {
	// Internal Protocol ID
	// Example: NS-001
	Pid string `protobuf:"bytes,1,opt,name=pid" json:"pid,omitempty"`
	// Protocol's name
	// Example: negative stain
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// Brief description of the method
	// Example:
	// 2 micro liters of sample, wait for 60 seconds, blot with paper 3 times,
	// 2 micro liters of uranyl acetate, wait for 60 seconds, blot with paper 3 times.
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	// List of labs associated with the sample collection
	// Example: [ Dexter Labs ]
	Lab []string `protobuf:"bytes,4,rep,name=lab" json:"lab,omitempty"`
	// List of name of the institution from the labs involved in sample collection
	// Example: [ Cartoon Network ]
	Institution []string `protobuf:"bytes,5,rep,name=institution" json:"institution,omitempty"`
	// List of people who developed the protocol
	// Example: [ Charlie, Doug ]
	DevelopedBy []string `protobuf:"bytes,6,rep,name=developedBy" json:"developedBy,omitempty"`
}

func (m *Tmpl_00000000DEADBEEF) Reset()                    { *m = Tmpl_00000000DEADBEEF{} }
func (m *Tmpl_00000000DEADBEEF) String() string            { return proto.CompactTextString(m) }
func (*Tmpl_00000000DEADBEEF) ProtoMessage()               {}
func (*Tmpl_00000000DEADBEEF) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *Tmpl_00000000DEADBEEF) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *Tmpl_00000000DEADBEEF) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tmpl_00000000DEADBEEF) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Tmpl_00000000DEADBEEF) GetLab() []string {
	if m != nil {
		return m.Lab
	}
	return nil
}

func (m *Tmpl_00000000DEADBEEF) GetInstitution() []string {
	if m != nil {
		return m.Institution
	}
	return nil
}

func (m *Tmpl_00000000DEADBEEF) GetDevelopedBy() []string {
	if m != nil {
		return m.DevelopedBy
	}
	return nil
}

func init() {
	proto.RegisterType((*Tmpl_00000000DEADBEEF)(nil), "oip5.record.templates.tmpl_00000000DEADBEEF")
}

func init() { proto.RegisterFile("tmpl_0000000deadbeef.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xc1, 0xca, 0xc2, 0x30,
	0x10, 0x84, 0xe9, 0xdf, 0xfe, 0x05, 0xe3, 0x45, 0x02, 0x85, 0xe0, 0xa9, 0x78, 0xf2, 0x54, 0x0a,
	0xe2, 0x03, 0x58, 0x5a, 0x1f, 0xc0, 0xa3, 0x17, 0x49, 0x9a, 0x15, 0x02, 0x69, 0xb3, 0xa4, 0xab,
	0xe0, 0x83, 0xf9, 0x7e, 0x92, 0xf4, 0x92, 0x3d, 0x0d, 0xdf, 0xec, 0x0c, 0x0c, 0xdb, 0xd3, 0x84,
	0xf6, 0xd1, 0xae, 0xa7, 0x41, 0x6a, 0x05, 0xf0, 0x6c, 0xd0, 0x3b, 0x72, 0xbc, 0x72, 0x06, 0xcf,
	0x8d, 0x87, 0xd1, 0x79, 0xdd, 0x10, 0x4c, 0x68, 0x25, 0xc1, 0x72, 0xf8, 0x66, 0xac, 0x4a, 0x53,
	0x6d, 0x3f, 0x5c, 0xfa, 0x6e, 0x18, 0xae, 0x7c, 0xc7, 0x72, 0x34, 0x5a, 0x64, 0x75, 0x76, 0xdc,
	0xdc, 0x82, 0xe4, 0x9c, 0x15, 0xb3, 0x9c, 0x40, 0xfc, 0x45, 0x14, 0x35, 0xaf, 0xd9, 0x56, 0xc3,
	0x32, 0x7a, 0x83, 0x64, 0xdc, 0x2c, 0xf2, 0x68, 0xa5, 0x28, 0xf4, 0x58, 0xa9, 0x44, 0x51, 0xe7,
	0xa1, 0xc7, 0x4a, 0x15, 0x32, 0x66, 0x5e, 0xc8, 0xd0, 0x2b, 0x66, 0xfe, 0xa3, 0x93, 0xa2, 0xb5,
	0xf5, 0x0d, 0xd6, 0x21, 0xe8, 0xee, 0x23, 0xca, 0xf5, 0x23, 0x41, 0x5d, 0x79, 0x2f, 0xc2, 0x20,
	0x55, 0xc6, 0x75, 0xa7, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x06, 0x3e, 0xb2, 0xfb, 0x00,
	0x00, 0x00,
}
