// Code generated by protoc-gen-go. DO NOT EDIT.
// source: historian.proto

/*
Package historian is a generated protocol buffer package.

It is generated from these files:
	historian.proto

It has these top-level messages:
	HistorianDataPoint
	HistorianPayout
*/
package historian

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HistorianDataPoint struct {
	Version                  int32   `protobuf:"varint,1,opt,name=Version" json:"Version,omitempty"`
	PubKey                   []byte  `protobuf:"bytes,2,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
	MiningRigRentalsLast10   float64 `protobuf:"fixed64,3,opt,name=MiningRigRentalsLast10" json:"MiningRigRentalsLast10,omitempty"`
	MiningRigRentalsLast24Hr float64 `protobuf:"fixed64,4,opt,name=MiningRigRentalsLast24Hr" json:"MiningRigRentalsLast24Hr,omitempty"`
	AutominerPoolHashrate    float64 `protobuf:"fixed64,5,opt,name=AutominerPoolHashrate" json:"AutominerPoolHashrate,omitempty"`
	FloNetHashRate           float64 `protobuf:"fixed64,6,opt,name=FloNetHashRate" json:"FloNetHashRate,omitempty"`
	FloMarketPriceBTC        float64 `protobuf:"fixed64,7,opt,name=FloMarketPriceBTC" json:"FloMarketPriceBTC,omitempty"`
	FloMarketPriceUSD        float64 `protobuf:"fixed64,8,opt,name=FloMarketPriceUSD" json:"FloMarketPriceUSD,omitempty"`
	LtcMarketPriceUSD        float64 `protobuf:"fixed64,9,opt,name=LtcMarketPriceUSD" json:"LtcMarketPriceUSD,omitempty"`
	NiceHashLast             float64 `protobuf:"fixed64,10,opt,name=NiceHashLast" json:"NiceHashLast,omitempty"`
	NiceHash24Hr             float64 `protobuf:"fixed64,11,opt,name=NiceHash24hr" json:"NiceHash24hr,omitempty"`
}

func (m *HistorianDataPoint) Reset()                    { *m = HistorianDataPoint{} }
func (m *HistorianDataPoint) String() string            { return proto.CompactTextString(m) }
func (*HistorianDataPoint) ProtoMessage()               {}
func (*HistorianDataPoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HistorianDataPoint) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *HistorianDataPoint) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *HistorianDataPoint) GetMiningRigRentalsLast10() float64 {
	if m != nil {
		return m.MiningRigRentalsLast10
	}
	return 0
}

func (m *HistorianDataPoint) GetMiningRigRentalsLast24Hr() float64 {
	if m != nil {
		return m.MiningRigRentalsLast24Hr
	}
	return 0
}

func (m *HistorianDataPoint) GetAutominerPoolHashrate() float64 {
	if m != nil {
		return m.AutominerPoolHashrate
	}
	return 0
}

func (m *HistorianDataPoint) GetFloNetHashRate() float64 {
	if m != nil {
		return m.FloNetHashRate
	}
	return 0
}

func (m *HistorianDataPoint) GetFloMarketPriceBTC() float64 {
	if m != nil {
		return m.FloMarketPriceBTC
	}
	return 0
}

func (m *HistorianDataPoint) GetFloMarketPriceUSD() float64 {
	if m != nil {
		return m.FloMarketPriceUSD
	}
	return 0
}

func (m *HistorianDataPoint) GetLtcMarketPriceUSD() float64 {
	if m != nil {
		return m.LtcMarketPriceUSD
	}
	return 0
}

func (m *HistorianDataPoint) GetNiceHashLast() float64 {
	if m != nil {
		return m.NiceHashLast
	}
	return 0
}

func (m *HistorianDataPoint) GetNiceHash24Hr() float64 {
	if m != nil {
		return m.NiceHash24Hr
	}
	return 0
}

type HistorianPayout struct {
	Version int32 `protobuf:"varint,1,opt,name=Version" json:"Version,omitempty"`
}

func (m *HistorianPayout) Reset()                    { *m = HistorianPayout{} }
func (m *HistorianPayout) String() string            { return proto.CompactTextString(m) }
func (*HistorianPayout) ProtoMessage()               {}
func (*HistorianPayout) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HistorianPayout) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func init() {
	proto.RegisterType((*HistorianDataPoint)(nil), "historian.HistorianDataPoint")
	proto.RegisterType((*HistorianPayout)(nil), "historian.HistorianPayout")
}

func init() { proto.RegisterFile("historian.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcf, 0x4b, 0x02, 0x41,
	0x14, 0xc7, 0xd9, 0x4c, 0xcd, 0x49, 0x92, 0x06, 0x92, 0x39, 0x8a, 0x87, 0x10, 0x0a, 0x35, 0x93,
	0x0e, 0x75, 0xca, 0x44, 0x84, 0x54, 0x96, 0x35, 0x3b, 0x74, 0x1b, 0xb7, 0x61, 0xf7, 0xd1, 0x3a,
	0x4f, 0x66, 0xdf, 0x12, 0xfe, 0xcb, 0xfd, 0x15, 0x31, 0x5b, 0x2e, 0xf9, 0xab, 0xcb, 0x30, 0xef,
	0xfb, 0xf9, 0x3c, 0x98, 0xe1, 0x3d, 0x56, 0x09, 0x21, 0x26, 0x34, 0x20, 0x75, 0x73, 0x69, 0x90,
	0x90, 0x97, 0xb2, 0xa0, 0xfe, 0x95, 0x63, 0x7c, 0xb8, 0xae, 0xfa, 0x92, 0xa4, 0x8b, 0xa0, 0x89,
	0x0b, 0x56, 0x7c, 0x55, 0x26, 0x06, 0xd4, 0xc2, 0xa9, 0x39, 0x8d, 0xbc, 0xb7, 0x2e, 0x79, 0x95,
	0x15, 0xdc, 0x64, 0xfe, 0xac, 0x56, 0xe2, 0xa8, 0xe6, 0x34, 0xca, 0xde, 0x6f, 0xc5, 0xef, 0x58,
	0x75, 0x0c, 0x1a, 0x74, 0xe0, 0x41, 0xe0, 0x29, 0x4d, 0x32, 0x8a, 0x47, 0x32, 0xa6, 0x9b, 0xb6,
	0xc8, 0xd5, 0x9c, 0x86, 0xe3, 0x1d, 0xa0, 0xfc, 0x9e, 0x89, 0x7d, 0xa4, 0xd3, 0x1d, 0x1a, 0x71,
	0x9c, 0x76, 0x1e, 0xe4, 0xbc, 0xcb, 0x2e, 0x1e, 0x13, 0xc2, 0x05, 0x68, 0x65, 0x5c, 0xc4, 0x68,
	0x28, 0xe3, 0xd0, 0x48, 0x52, 0x22, 0x9f, 0x36, 0xee, 0x87, 0xfc, 0x92, 0x9d, 0x0d, 0x22, 0x9c,
	0x28, 0xb2, 0x89, 0x67, 0xf5, 0x42, 0xaa, 0x6f, 0xa5, 0xfc, 0x9a, 0x9d, 0x0f, 0x22, 0x1c, 0x4b,
	0xf3, 0xa1, 0xc8, 0x35, 0xe0, 0xab, 0xde, 0xcb, 0x93, 0x28, 0xa6, 0xea, 0x2e, 0xd8, 0xb5, 0x67,
	0xd3, 0xbe, 0x38, 0xd9, 0x67, 0xcf, 0xa6, 0x7d, 0x6b, 0x8f, 0xc8, 0xdf, 0xb2, 0x4b, 0x3f, 0xf6,
	0x0e, 0xe0, 0x75, 0x56, 0x9e, 0x80, 0xaf, 0xec, 0xcb, 0xec, 0xdf, 0x05, 0x4b, 0xc5, 0x8d, 0xec,
	0xaf, 0xd3, 0xe9, 0x86, 0x46, 0x9c, 0x6e, 0x3a, 0x36, 0xab, 0x5f, 0xb1, 0x4a, 0x36, 0x6b, 0x57,
	0xae, 0x30, 0xf9, 0x67, 0xd0, 0xbd, 0xce, 0x5b, 0x3b, 0x00, 0x0a, 0x93, 0x79, 0xd3, 0xc7, 0x45,
	0x0b, 0x61, 0xf9, 0x19, 0xd8, 0xb3, 0xb5, 0xc0, 0xf7, 0x24, 0x52, 0x71, 0x2b, 0xdb, 0xa1, 0x87,
	0xec, 0x36, 0x2f, 0xa4, 0xfb, 0x75, 0xfb, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xd0, 0xad, 0x23, 0xe7,
	0x72, 0x02, 0x00, 0x00,
}
